services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: spherych_devapp
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
